interface MenuItem {
  name: string;
  price: string;
}

export const sushiAppetizer: MenuItem[] = [
  { name: "Blacken Tuna Taco", price: "$14.00" },
  { name: "Honey Wasabi Tuna", price: "$17.00" },
  { name: "Kani Salad", price: "$9.00" },
  { name: "New World Sashimi", price: "$14.00" },
  { name: "Oshinko Appetizer", price: "$6.00" },
  { name: "Peppered Salmon", price: "$17.00" },
  { name: "Salmon Pizza", price: "$16.00" },
  { name: "Salmon Sashimi Bites", price: "$15.00" },
  { name: "Salmon two way", price: "$14.00" },
  { name: "Seaweed Salad", price: "$8.00" },
  { name: "Spicy Crunchy Seafood Salad", price: "$12.00" },
  { name: "Treasure Island", price: "$15.00" },
  { name: "Tuna Pizza", price: "$17.00" },
  { name: "Tuna Tartare", price: "$15.00" },
  { name: "Tuna Tataki", price: "$17.00" },
  { name: "Tuna Tower", price: "$16.00" },
  { name: "Yellowtail Jalapeno APP", price: "$16.00" },
  { name: "Salmon Tartar", price: "$14.00" },
  { name: "Salmon Skin Salad", price: "$10.00" },
  { name: "Spicy Tuna Crispy Rice", price: "$20.00" },
];

export const sushiPlatter: MenuItem[] = [
  { name: "Chirashi", price: "$30.00" },
  { name: "House Sashimi", price: "$32.00" },
  { name: "Imperial Sashimi", price: "$36.00" },
  { name: "Roll A", price: "$21.00" },
  { name: "Roll B", price: "$24.00" },
  { name: "Tengda Platter A", price: "$45.00" },
  { name: "Tengda Platter A", price: "$72.00" },
  { name: "Trio Color Sushi", price: "$36.00" },
  { name: "Sushi A", price: "$27.00" },
  { name: "Sushi B", price: "$30.00" },
  { name: "Sushi C", price: "$35.00" },
  { name: "Small Boat", price: "$85.00" },
  { name: "Large Boat", price: "$175.00" },
  { name: "Salmon Don", price: "$28.00" },
  { name: "Tekka Don", price: "$30.00" },
  { name: "Unagi Don", price: "$32.00" },
];


export const rollAndHandRolls: MenuItem[] = [
  { name: "Asparagus Roll", price: "$5.00" },
  { name: "Avocado Cucumber Roll", price: "$5.00" },
  { name: "Avocado Roll", price: "$5.00" },
  { name: "Blackened Tuna Roll", price: "$10.00" },
  { name: "California Roll", price: "$7.00" },
  { name: "Cashew & Potato Roll", price: "$5.00" },
  { name: "Crab Stick Roll", price: "$7.00" },
  { name: "Cucumber Roll", price: "$5.00" },
  { name: "Eel Avocado Roll", price: "$9.00" },
  { name: "Eel Cucumber Roll", price: "$9.00" },
  { name: "Futo Maki Roll", price: "$8.00" },
  { name: "Honey Boston Roll", price: "$8.00" },
  { name: "Oshinko Roll", price: "$5.00" },
  { name: "Peanut Avocado Roll", price: "$5.00" },
  { name: "Philadelphia Roll", price: "$8.00" },
  { name: "Rice Roll", price: "$5.00" },
  { name: "Salmon Avocado Roll", price: "$7.00" },
  { name: "Salmon Cucumber Roll", price: "$7.00" },
  { name: "Salmon Roll", price: "$7.00" },
  { name: "Salmon Skin Roll", price: "$8.00" },
  { name: "Shiitake Mushroom Roll", price: "$6.00" },
  { name: "Shrimp Asparagus Roll", price: "$7.00" },
  { name: "Shrimp Avocado Roll", price: "$7.00" },
  { name: "Shrimp Cucumber Roll", price: "$7.00" },
  { name: "Shrimp Mango Roll", price: "$7.00" },
  { name: "Shrimp Tempura Roll", price: "$10.00" },
  { name: "Smoked Salmon Roll", price: "$8.00" },
  { name: "Spicy Crab Salad Roll", price: "$7.00" },
  { name: "Spicy Crunchy Salmon Roll", price: "$9.00" },
  { name: "Spicy Crunchy Tuna Roll", price: "$9.00" },
  { name: "Spicy Rock Shrimp Avocado Roll", price: "$11.95" },
  { name: "Spicy Salmon Roll", price: "$9.00" },
  { name: "Spicy Salmon Skin Roll", price: "$8.00" },
  { name: "Spicy Scallop Roll", price: "$14.00" },
  { name: "Spicy Shrimp Roll", price: "$8.00" },
  { name: "Spicy Tuna Roll", price: "$8.00" },
  { name: "Spicy Yellowtail Roll", price: "$9.00" },
  { name: "Sweet Potato Roll", price: "$5.00" },
  { name: "Tamago Roll", price: "$5.00" },
  { name: "Tobiko Roll", price: "$12.00" },
  { name: "Tuna Avocado Roll", price: "$8.00" },
  { name: "Tuna Cucumber Roll", price: "$8.00" },
  { name: "Tuna Jalapeno Roll", price: "$8.00" },
  { name: "Tuna Roll", price: "$7.00" },
  { name: "Vegetable Roll", price: "$5.00" },
  { name: "White Tuna Jalapeno Roll", price: "$7.00" },
  { name: "Yellowtail Jalapeno Roll", price: "$7.00" },
  { name: "Yellowtail Scallion Roll", price: "$7.00" },
  { name: "Cashew & Avocado Roll", price: "$5.00" },
  { name: "Avo & Inari Roll", price: "$6.00" },
]

export const soup: MenuItem[] = [
  { name: "SM Hot & Sour Soup", price: "$5.00" },
  { name: "SM Shrimp & Pork Dumpling Soup", price: "$6.00" },
  { name: "SM Miso Soup", price: "$4.00" },
  { name: "SM Clear Soup", price: "$5.00" },
  { name: "LG Chicken Corn Soup", price: "$11.00" },
  { name: "LG Veggie Tofu Soup", price: "$10.00" },
  { name: "LG House Special Soup", price: "$12.00" },
  { name: "LG Hot & Sour Soup", price: "$9.00" },
  { name: "LG Shrimp & Pork Dumpling Soup", price: "$11.00" },
  { name: "LG Miso Soup", price: "$8.00" },
  { name: "LG Clear Soup", price: "$9.00" }
];

export const salad: MenuItem[] =  [
  { name: "Avocado Salad", price: "$11.00" },
  { name: "Blacken Tuna Salad", price: "$16.00" },
  { name: "Caesar Salad", price: "$8.60+" },
  { name: "Green Salad", price: "$6.69" },
  { name: "Chicken Mango Salad", price: "$13.00" },
  { name: "Shrimp Mango Salad", price: "$15.00" },
  { name: "Tempura Onion & Avocado Salad", price: "$11.00" },
  { name: "Kani Salad", price: "$8.00" },
  { name: "Seaweed Salad", price: "$8.00" },
  { name: "Crispy Salmon Skin Salad", price: "$9.00" }
];

export const appetizer: MenuItem[] =  [
  { name: "3 Star Dumplings", price: "$15.00" },
  { name: "BBQ Babyback Ribs", price: "$14.00" },
  { name: "Thai Chicken Lettuce Wraps", price: "$14.00" },
  { name: "Veggie Spring Roll", price: "$3.25" },
  { name: "Chicken Spring Roll", price: "$4.00" },
  { name: "Cold Sesame Noodles", price: "$7.00" },
  { name: "Firecracker Shrimp", price: "$12.00" },
  { name: "Grill Boneless Shortribs", price: "$13.00" },
  { name: "Scallion Pancake", price: "$8.00" },
  { name: "Edamame", price: "$6.00" },
  { name: "Spicy Garlic Edamame", price: "$10.00" },
  { name: "Homemade Pork Dumpling", price: "$12.00" },
  { name: "Gyoza", price: "$9.00" },
  { name: "Szechuan Dumpling", price: "$12.00" },
  { name: "Veggie Tempura", price: "$10.00" },
  { name: "Shrimp Veggie Tempura", price: "$10.00" },
  { name: "Shrimp Tempura", price: "$10.00" },
  { name: "Pork Buns", price: "$13.00" },
  { name: "Duck Buns", price: "$14.00" },
  { name: "Shu Mai", price: "$9.00" },
  { name: "Veggie Dumpling", price: "$9.00" },
  { name: "Chicken Satay", price: "$11.00" },
  { name: "Steam Buns", price: "$4.00" }
];

export const sushiSashimi: MenuItem[] =  [
  { name: "Black Tobiko", price: "$3.50" },
  { name: "Blackened Tuna", price: "$3.50" },
  { name: "Botan Ebi", price: "$6.00" },
  { name: "Cooked Shrimp", price: "$3.50" },
  { name: "Crab Stick", price: "$3.50" },
  { name: "Eel", price: "$3.50" },
  { name: "Egg Omelet", price: "$3.00" },
  { name: "Fluke", price: "$3.50" },
  { name: "Flying Fish Roe", price: "$3.50" },
  { name: "Ikura", price: "$5.00" },
  { name: "Inari", price: "$3.00" },
  { name: "King Salmon", price: "$6.00" },
  { name: "Mackerel", price: "$2.75" },
  { name: "Octopus", price: "$3.50" },
  { name: "Red Clam", price: "$3.50" },
  { name: "Red Snapper", price: "$5.00" },
  { name: "Scallop", price: "$4.50" },
  { name: "Salmon", price: "$3.50" },
  { name: "Smoked Salmon", price: "$5.00" },
  { name: "Spicy Salmon", price: "$4.50" },
  { name: "Spicy Scallop", price: "$4.50" },
  { name: "Spicy Tuna", price: "$4.50" },
  { name: "Squid", price: "$3.50" },
  { name: "Stripe Bass", price: "$3.50" },
  { name: "Sweet Shrimp", price: "$5.00" },
  { name: "Toro", price: "$10.00" },
  { name: "Tuna", price: "$3.50" },
  { name: "Uni", price: "$12.00" },
  { name: "Wasabi Tobiko", price: "$3.50" },
  { name: "White Tuna", price: "$3.50" },
  { name: "Yellowtail", price: "$3.50" }
];

export const specialRolls: MenuItem[] =  [
  { name: "Almond Dragon Roll", price: "$19.00" },
  { name: "Amy Roll", price: "$19.00" },
  { name: "Angel Roll", price: "$19.00" },
  { name: "Black Dragon Roll", price: "$19.00" },
  { name: "Deluxe Cajun Roll", price: "$19.00" },
  { name: "Deluxe Lobster Roll", price: "$29.00" },
  { name: "Deluxe Rainbow Roll", price: "$18.00" },
  { name: "Dreamy Paris Roll", price: "$19.00" },
  { name: "Dynamite Roll", price: "$18.00" },
  { name: "Emperor Roll", price: "$19.00" },
  { name: "Fairfield Roll", price: "$19.00" },
  { name: "Fire Island Roll", price: "$22.00" },
  { name: "Godzilla Roll", price: "$19.00" },
  { name: "Green Dragon Roll", price: "$19.00" },
  { name: "Hurricane Roll", price: "$21.00" },
  { name: "James Roll", price: "$19.00" },
  { name: "Jimmy Roll", price: "$19.00" },
  { name: "Joe Roll", price: "$19.00" },
  { name: "Kelly Roll", price: "$19.00" },
  { name: "Kerri Roll", price: "$21.00" },
  { name: "King Roll", price: "$19.00" },
  { name: "Lobster Tempura Roll", price: "$27.00" },
  { name: "Magical Roll", price: "$19.00" },
  { name: "Phoenix Roll", price: "$20.00" },
  { name: "Post Roll", price: "$19.00" },
  { name: "Rainbow Tobiko Roll", price: "$19.00" },
  { name: "Salmon Lover’s Roll", price: "$19.00" },
  { name: "Spider Roll", price: "$17.00" },
  { name: "Sammy Roll", price: "$19.00" },
  { name: "Sweet Heart ❤ Roll", price: "$19.00" },
  { name: "Tengda Roll", price: "$22.00" },
  { name: "Tootsie Roll", price: "$19.00" },
  { name: "Tuna Lovers Roll", price: "$18.00" },
  { name: "Westport Roll", price: "$19.00" },
  { name: "White Fish Temp Roll", price: "$11.00" }
];
export const kidHibAndSides: MenuItem[] =  [
  { name: "Kid HIB Chicken", price: "$15.95" },
  { name: "Kid HIB Shrimp", price: "$17.95" },
  { name: "Kid HIB Salmon", price: "$17.95" },
  { name: "Kid HIB Steak", price: "$18.95" },
  { name: "Side Chicken",price: "$11.00" },
  { name: "Side Shrimp",price: "$12.00" },
  { name: "Side Salmon", price: "$12.00" },
  { name: "Side Scallop", price: "$15.00" },
  { name: "Side Steak", price: "$14.00" },
  { name: "Side Filet Mignon", price: "$16.00" },
  { name: "HIB Fried Rice", price: "$6.00" },
  { name: "HIB Noodle", price: "$6.00" },
  { name: "Small White Rice", price: "$2.00" },
  { name: "Lg White Rice", price: "$4.00" },
  { name: "Small Brown Rice", price: "$2.00" },
  { name: "Lg Brown Rice", price: "$4.00" },
  { name: "Sushi Rice", price: "$3.00" },
  { name: "Ginger Dressing", price: "$1.15+" },
  { name: "Hot Oil", price: "$1.15+" },
  { name: "Japanese Soda(Strawberry)", price: "$5.00" },
  { name: "Japanese Soda", price: "$5.00" }
];

export const tasteOfAsia: MenuItem[] =  [
  { name: "Broccoli soy ginger sauce", price: "N/A" },
  { name: "Wok Mix Vegetables", price: "N/A" },
  { name: "Garlic Sauce", price: "N/A" },
  { name: "Black Bean Sauce", price: "N/A" },
  { name: "Eggplant w spicy Garlic Sauce", price: "N/A" },
  { name: "Fresh Mushroom", price: "N/A" },
  { name: "Peanut spicy sauce", price: "N/A" },
  { name: "String Beans", price: "N/A" },
  { name: "Ginger Scallion", price: "N/A" },
  { name: "Wok Glazed Ginger", price: "N/A" },
  { name: "Thai Curry Sauce", price: "N/A" },
  { name: "Snow Peas", price: "N/A" },
  { name: "Cashew Nut", price: "N/A" },
  { name: "Moo Shu", price: "N/A" },
  { name: "Double Cooked Pork", price: "$17.00" },
  { name: "Sliced Pork with Onion", price: "$17.00" },
  { name: "Sliced Pork w. Garlic Sauce", price: "$17.00" },
  { name: "Sliced Pork w. Black Bean Sauce", price: "$17.00" },
  { name: "Ma Po Tofu", price: "$15.00" }
];
export const healthyDiet: MenuItem[] =  [
    { name: "Steam Mix Vegetables", price: "$15.95" },
    { name: "Steam Mix Veggie Chicken", price: "$17.95" },
    { name: "Steam Mix Veggie Shrimp", price: "$23.95" },
    { name: "Steam Mix Vegetable Scallop", price: "$28.95" },
    { name: "Steam Veg Chk/Shrimp/Scallop", price: "$30.95" },
    { name: "Steam Broccoli", price: "$14.95" },
    { name: "Steam Chicken & Broccoli", price: "$17.95" },
    { name: "Steam Beef & Broccoli", price: "$19.95" },
    { name: "Steam Shrimp & Broccoli", price: "$23.95" },
    { name: "Steam Scallop & Broccoli", price: "$28.95" },
    { name: "Steam Broccoli Chk/Shrimp/Scallop", price: "$30.95" }
  ]
export const soda: MenuItem[] =  [
    { name: "Coke", price: "$2.00" },
    { name: "Diet Coke", price: "$2.00" },
    { name: "Sprite", price: "$2.00" },
    { name: "Ginger Ale", price: "$2.00" },
    { name: "Ice Green Tea", price: "$2.50" },
    { name: "Ice Tea (unsweetened)", price: "$2.50" },
    { name: "Spring Water", price: "$2.00" },
    { name: "Mixed Juice", price: "$4.00" },
    { name: "Sparkling water", price: "$5.00" },
    { name: "Sparkling water", price: "$7.00" },
    { name: "Japanese Soda(Strawberry)", price: "$5.00" },
    { name: "Japanese Soda", price: "$5.00" }
  ];
